version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api_glossary
    restart: always
    depends_on:
      elastic:
        condition: "service_started"
    volumes:
      - /home/admin01/vadim/glossary:/app
    ports:
      - "8501:80"
    networks:
      - elastic
    links:
      - elastic
    command: ["streamlit", "run", "app.py"]

  elastic:
    image: elastic/elasticsearch:8.9.1
    container_name: elastic_glossary
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
    networks:
      - elastic
    volumes:
      - es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 4000M

networks:
  elastic:
    driver: bridge

volumes:
  es-data:
    driver: local